### ISSUE TITLE
XNCOAISNレビュー：Portfoliosのコンテンツ部分の別の実装方法(row,colを無くす)

### ISSUE THREAD

**Issue by pitang1965** [pitang1965/next-portfolio#11]
#7 を分離

const numbersToShow =
    router.pathname === "/" ? (isMobileUi ? 3 : 6) : (isMobileUi ? 4 : 9);
```

flexでアイテムの幅を指定する方法
```
<Group spacing={0}>
  {portfolioData.slice(0, numbersToShow).map((portfolio) => (
    <Box
      key={portfolio.id}
      sx={(theme) => ({
        width: isMobileUi ? "100%" : "33.333%",
      })}
    >
      <PortfolioCard data={portfolio} />
    </Box>
  ))}
</Group>
```

flexでアイテムの幅を指定する方法(Mantineのブレークポイントを使う)
```
<Group spacing={0}>
  {portfolioData.slice(0, numbersToShow).map((portfolio) => (
    <Box
      key={portfolio.id}
      sx={(theme) => ({
        width: "100%",
        [theme.fn.largerThan("sm")]: {
          width: "50%",
        },
        [theme.fn.largerThan("md")]: {
          width: "33.333%",
        }
      })}
    >
      <PortfolioCard data={portfolio} />
    </Box>
  ))}
</Group>
```

gridで最小幅を指定してカラム数は自動で変わる方法
```
<Box
  sx={(theme) => ({
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
  })}
>
  {portfolioData.slice(0, numbersToShow).map((portfolio) => (
    <PortfolioCard key={portfolio.id} data={portfolio} />
  ))}
</Box>
```

**Comment by pitang1965** [comment]
@XNCOAISN
教えていただいた2番目の方法を採用させていただきました。
typoの指摘もありがとうございます。![bitmoji](https://sdk.bitmoji.com/render/panel/a76304ed-1e39-4e61-8f0b-4f6f88296aa1-4012260f-07f3-4d6c-a2f4-3413579a63c6-v1.png?transparent=1&palette=1&width=246)

**Comment by pitang1965** [comment]
@XNCOAISN
こちら、/portfolio は問題ないのですが、/のほう、Portfolio の横幅が狭くなってしまいました。<Box>にCSS指定したり、Gridに戻したりしても、解決できず1時間以上経過しています。![bitmoji](https://sdk.bitmoji.com/render/panel/60e2626e-b078-4a7a-868e-5b13aee763ee-4012260f-07f3-4d6c-a2f4-3413579a63c6-v1.png?transparent=1&palette=1&width=246)

**Comment by pitang1965** [comment]
@XNCOAISN
やっと直せました。おかしくなる原因はよくわかりません。
Boxを撤去しました。

**Comment by pitang1965** [comment]
@XNCOAISN
申し訳ありません。意図通りの動きをしていませんでした。

**Comment by XNCOAISN** [comment]
@pitang1965 
Portfolios, PortfolioSectionのContainerに width: "100%" でいけそうです。

Blogもコンテンツが短いと幅が狭くなるのでそちらも修正

**Comment by pitang1965** [comment]
やっと直りました。ありがとうございます。
![bitmoji](https://sdk.bitmoji.com/render/panel/1393d68b-2fdb-4cc3-825b-1190fb987612-4012260f-07f3-4d6c-a2f4-3413579a63c6-v1.png?transparent=1&palette=1&width=246)
