### ISSUE TITLE
Twitterプロフィール画像URLをAPIから取得する

### ISSUE THREAD

**Issue by makkenno** [pitang1965/next-portfolio#45]
現状の仕様に特にこだわりなどなければTweet表示部のプロフィール画像URLはベタ書きではなく、APIから取得する方が良いと思いました！

**Comment by pitang1965** [comment]
Commitメッセージに#つけるのを忘れてしまったのですが、上記変更に加えて、以下の変更をして、Twitterプロフィール画像URLをAPIから取得するようにしました。
https://github.com/pitang1965/next-portfolio/commit/80292d18a2321eca347d136bbcef8f32877d8194
