### ISSUE TITLE
Twitterカード部のアカウント名がリンクになっていない

### ISSUE THREAD

**Issue by makkenno** [pitang1965/next-portfolio#46]
Twitterカードのアカウント名（ピータン@〜の部分）がリンクになっていませんでした！
その他の部分はリンクになっていたため、意図的なものではないと判断した次第です

**Comment by pitang1965** [comment]
こちら、カード全体にツイートへのハイパーリンクを設定しました。
以前は、細かくプロフィールページとツイートへリンクを切り分けていたのですが、やめてシンプルにしました。

気づきづらいところ、ご指摘ありがとうございました。
![bitmoji](https://sdk.bitmoji.com/render/panel/a76304ed-1e39-4e61-8f0b-4f6f88296aa1-4012260f-07f3-4d6c-a2f4-3413579a63c6-v1.png?transparent=1&palette=1&width=246)
